apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: ON_WITH_INCLUSION
  inclusion:
    services: ["orders-service.default.svc.cluster.local","inventory-service.default.svc.cluster.local"]
