version: '3'
services:
 nginx:
  image: nginx:alpine
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
  - "8080:8080"
  depends_on:
  - "socat"
 socat:
  image: alpine/socat
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  ports:
  - "2345:2345"
  command: TCP-L:2345,fork,reuseaddr,bind=socat UNIX:/var/run/docker.sock
