apiVersion: apps/v1
kind: Deployment
metadata:
  name: sts-deployment 
  labels:
    app: sts 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sts
  template:
    metadata:
      labels:
        app: sts
    spec:
      containers:
      - name: sts
        image: prabath/secure-sts-ch10:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: application-properties
            mountPath: "/opt/application.properties"
            subPath: "application.properties"
          - name: keystore
            mountPath: "/opt/keystore.jks"
            subPath: "keystore.jks"
          - name: jwt-keystore
            mountPath: "/opt/jwt.jks"
            subPath: "jwt.jks"
        env:
          - name: KEYSTORE_SECRET
            valueFrom:
              configMapKeyRef:
                name: sts-keystore-credentials
                key: KEYSTORE_PASSWORD
          - name: JWT_KEYSTORE_SECRET
            valueFrom:
              configMapKeyRef:
                name: sts-keystore-credentials
                key: JWT_KEYSTORE_PASSWORD       
      volumes:
        - name: application-properties
          configMap:
            name: sts-application-properties-config-map
        - name: keystore
          configMap:
            name: sts-keystore-config-map
        - name: jwt-keystore
          configMap:
            name: sts-jwt-keystore-config-map
