apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ecomm-authn-policy
spec:
  targets:
  - name: orders-service
  - name: inventory-service
  peers:
  - mtls:
      mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ecomm-authn-istio-gateway-mtls
  namespace: istio-system
spec:
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ecomm-authn-service-mtls
spec:
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL